
degree = 1.0

suppress_bg = false

flow_scales = ['upper_2']

divider = 20

reshape_ckpt_path = 'models/body_reshape_model.pth'


src_dir = './test_cases'
gt_dir = 'null'
save_dir = 'test_cases_output'

